import Foundation

/// Maps application names to SF Symbol names for consistent icon rendering
enum IconStyle: String, Decodable {
    case appIcon = "app-icon"  // Original NSApp icons (with backgrounds)
    case sfSymbol = "sf-symbol"  // SF Symbols (glyph-only, no background, tints properly)
}

struct AppIconMapper {
    /// Comprehensive mapping of app names to specific SF Symbols that match app logos
    /// These are glyph-only symbols without backgrounds - perfect for tinting
    private static let symbolMappings: [String: String] = [
        "1Password": "key.fill",
        "1Password 8": "key.fill",
        "Ableton Live": "slider.horizontal.3",
        "Acrobat": "doc.richtext",
        "Activity Monitor": "speedometer",
        "Actual": "dollarsign.circle.fill",
        "Adobe Acrobat": "doc.plaintext",
        "Adobe Illustrator": "pen.tip",
        "Adobe InDesign": "text.insert",
        "Adobe Lightroom": "sun.max.trianglebadge.exclamationmark",
        "Adobe Photoshop": "paintbrush.pointed.fill",
        "Adobe Premiere": "scissors",
        "Adobe Premiere Pro 2024": "scissors",
        "Affinity": "paintpalette.fill",
        "Affinity Designer": "paintbrush.fill",
        "Affinity Designer 2": "paintbrush.fill",
        "Affinity Photo": "camera.metering.center.weighted.average",
        "Affinity Photo 2": "camera.metering.center.weighted.average",
        "Affinity Publisher": "doc.text.image.fill",
        "Affinity Publisher 2": "doc.text.image.fill",
        "After Effects": "sparkles.rectangle.stack.fill",
        "Airmail": "paperplane.circle.fill",
        "Aktivitätsanzeige": "speedometer",
        "Alacritty": "terminal.fill",
        "Alfred": "crown.fill",
        "Amazon Chime": "video.slash.fill",
        "Amie": "calendar",
        "AmneziaVPN": "shield.lefthalf.filled",
        "Amplenote": "music.note.list",
        "Android Emulator": "android.app.fill",
        "Android Messages": "message.fill",
        "Android Studio": "android.app.fill",
        "Antigravity": "arrow.up",
        "AnyDesk": "cursorarrow.square",
        "App Eraser": "eraser.fill",
        "AppCode": "at.circle.fill",
        "Apple Books": "sparkles.book.fill",
        "Apple Music": "music.quarternote.3",
        "Arc": "captions.bubble",
        "Atom": "atom",
        "Audacity": "waveform",
        "Automator": "gearshape.arrow.triangle.2.circlepath",
        "BBEdit": "text.justify.left",
        "Bambu Studio": "printer.fill",
        "Bartender": "menubar.dock.rectangle",
        "Battle.net": "shield.lefthalf.filled",
        "Bear": "bear.fill",
        "BetterTouchTool": "hand.tap.fill",
        "Bitwarden": "key.radiowaves.forward",
        "Blender": "cube.transparent.fill",
        "Bloom": "folder.fill",
        "Books": "book.fill",
        "Box": "archivebox.fill",
        "Brave": "lion",
        "Brave Browser": "lion",
        "CCleaner": "xmark.bin.fill",
        "CLion": "leaf.fill",
        "Calculator": "calculator",
        "Calculette": "calculator",
        "Calendar": "calendar",
        "Calendrier": "calendar",
        "Calibre": "books.vertical.fill",
        "Canary Mail": "envelope.fill",
        "Carbon Copy Cloner": "copy.fill",
        "ChatGPT": "brain.filled.head.profile",
        "ChatGPT Atlas": "message.fill",
        "Chromatix": "music.quarternote.3",
        "Chrome": "circle.hexagongrid.fill",
        "Cinema 4D": "cube.box.fill",
        "Claude": "brain.head.profile",
        "CleanMyMac X": "trash.circle.fill",
        "Clock": "deskclock.fill",
        "Code": "curlybraces.square",
        "Code - Insiders": "curlybraces.square",
        "Codex": "curlybraces.square",
        "Coinbase": "dollarsign.circle.fill",
        "ColorSync Utility": "paintpalette.fill",
        "Console": "terminal.fill",
        "Control Center": "switch.2",
        "Copilot": "brain.filled.head.profile",
        "Craft": "scissors.badge.ellipsis",
        "Creative Cloud": "cloud.fill",
        "Cron": "calendar",
        "Cursor": "cursorarrow.rays",
        "Cyberduck": "link.circle.fill",
        "DEVONthink": "curlybraces",
        "DEVONthink 3": "curlybraces",
        "DVD Player": "gamecontroller.fill",
        "DaVinci Resolve": "wand.and.stars.inverse",
        "DataGrip": "cylinder.split.1x2.fill",
        "Dictionary": "book.fill",
        "DingTalk": "message.fill",
        "Discord": "gamecontroller.fill",
        "Discord Canary": "gamecontroller.fill",
        "Discord PTB": "gamecontroller.fill",
        "Disk Utility": "internaldrive.fill",
        "Docker": "shippingbox.fill",
        "Docker Desktop": "shippingbox.fill",
        "Dropbox": "drop.triangle.fill",
        "Edge": "waveform.path.ecg",
        "Electron": "curlybraces.square",
        "Element": "atom",
        "Elgato Stream Deck": "button.programmable",
        "Epic Games": "staroflife.shield.fill",
        "Erinnerungen": "list.bullet.clipboard.fill",
        "Evernote": "notebook",
        "Excel": "tablecells.fill",
        "FL Studio": "knob",
        "FSNotes": "note.text",
        "FaceTime": "video.fill",
        "Facebook": "person.3.fill",
        "Fantastical": "calendar.badge.clock",
        "Figma": "square.split.2x1",
        "FileZilla": "arrow.up.arrow.down.square.fill",
        "Final Cut Pro": "film.fill",
        "Finder": "folder.fill",
        "Firefox": "flame",
        "Firefox Developer Edition": "flame",
        "Firefox Nightly": "flame",
        "Flux": "sun.max.fill",
        "Fork": "arrow.triangle.branch",
        "Fotos": "photo",
        "GOG Galaxy": "galaxy.fill",
        "Games": "gamecontroller.fill",
        "GarageBand": "guitars.fill",
        "Ghostty": "terminal.fill",
        "ghostty": "terminal.fill",
        "GitHub Desktop": "globe.americas.fill",
        "GitKraken": "network",
        "GoLand": "forward.fill",
        "GoodNotes": "hand.draw.fill",
        "Goodnotes": "note.text",
        "Google Chat": "message.fill",
        "Google Chrome": "circle.hexagongrid.fill",
        "Google Drive": "cloud.fill",
        "Google Maps": "map.fill",
        "HEY": "envelope.fill",
        "HTTPie": "flame.circle.fill",
        "Home Assistant": "house.lodge.fill",
        "IINA": "play.rectangle.fill",
        "Illustrator": "pen.tip",
        "Image Capture": "camera.on.rectangle.fill",
        "Image Playground": "photo",
        "InDesign": "text.insert",
        "Insomnia": "moon.zzz.fill",
        "Instagram": "camera.circle.fill",
        "IntelliJ IDEA": "square.stack.3d.up.fill",
        "JetBrains Rider": "figure.outdoor.cycle",
        "KakaoTalk": "message.fill",
        "Kalender": "calendar",
        "Karabiner-Elements": "keyboard.badge.ellipsis",
        "Karabiner-Elements Settings": "gearshape.2.fill",
        "Karten": "map.fill",
        "KeePassXC": "key.radiowaves.forward",
        "Keynote": "cursorarrow.click",
        "Kindle": "book.closed.fill",
        "LastPass": "key.horizontal.fill",
        "Lightroom": "sun.max.trianglebadge.exclamationmark",
        "Lightroom Classic": "sun.max.trianglebadge.exclamationmark",
        "Line": "message.fill",
        "LinkedIn": "person.crop.circle.badge.checkmark",
        "Little Snitch": "antenna.radiowaves.left.and.right.slash",
        "Live": "slider.horizontal.3",
        "Logic Pro": "pianokeys",
        "Logseq": "diagram.semi filled",
        "LuLu": "antenna.radiowaves.left.and.right.slash",
        "MPV": "play.circle.fill",
        "MacVim": "modal.key.fill",
        "Magnet": "magnet.fill",
        "Mail": "envelope.fill",
        "MailMate": "envelope.fill",
        "Mailspring": "envelope.fill",
        "Maps": "map.fill",
        "Mattermost": "message.and.waveform",
        "Messages": "message.fill",
        "Microsoft Edge": "waveform.path.ecg",
        "Microsoft Excel": "tablecells.fill",
        "Microsoft PowerPoint": "play.square.stack",
        "Microsoft Remote Desktop": "desktopcomputer.and.monitor",
        "Microsoft Teams": "person.2.wave.2",
        "Microsoft Teams (work or school)": "person.2.wave.2",
        "Microsoft To Do": "circle.hexagongrid.circle",
        "Microsoft Word": "doc.text.below.ecg",
        "Min": "globe",
        "MoneyMoney": "dollarsign.arrow.circlepath",
        "MongoDB Compass": "compass.drawing",
        "MonitorControl": "sun.max.fill",
        "Mullvad Browser": "globe",
        "Mullvad VPN": "shield.lefthalf.filled",
        "Music": "music.note.list",
        "Musik": "music.quarternote.3",
        "Musique": "music.quarternote.3",
        "MySQL Workbench": "wrench.and.hammer.fill",
        "Nachrichten": "message.fill",
        "NetEaseMusic": "music.note",
        "Nextcloud": "cloud.fill",
        "Night Shift": "moon.zzz.fill",
        "Noodl": "network",
        "NordVPN": "shield.lefthalf.filled",
        "Notability": "pencil.and.ruler.fill",
        "Notes": "note.text",
        "Notion": "doc.text.image",
        "Notion Calendar": "calendar",
        "Notion Mail": "envelope.open.text",
        "Notizen": "note.text",
        "Nova": "staroflife",
        "Numbers": "chart.bar.xaxis",
        "OBS": "video.circle.fill",
        "Obsidian": "sparkles",
        "Ollama": "brain.filled.head.profile",
        "OmniFocus": "target",
        "OneDrive": "cloud.fill",
        "OneNote": "notebook.square",
        "OnyX": "wrench.and.screwdriver.fill",
        "Open Video Downloader": "arrow.down.circle.fill",
        "OpenAI Translator": "bubble.left.and.bubble.right.text",
        "OpenVPN Connect": "lock.open.slash",
        "Opera": "o.circle",
        "OrbStack": "cube.box.fill",
        "OrcaSlicer": "printer.fill",
        "Origin": "gift.fill",
        "Orion": "star.circle",
        "Orion RC": "star.circle",
        "Outlook": "calendar.badge.clock",
        "Overcast": "antenna.radiowaves.left.and.right",
        "PDF Expert": "doc.richtext",
        "Pages": "doc.on.clipboard",
        "Parallels Desktop": "macbook.and.ipad",
        "Parcel": "package.fill",
        "Passepartout": "key.fill",
        "Password Depot": "key.fill",
        "Passwords": "key.horizontal.fill",
        "Paw": "pawprint.fill",
        "Pearcleaner": "trash.circle.fill",
        "Perplexity": "questionmark.circle.fill",
        "Perplexity AI": "play.fill",
        "Phone": "phone.fill",
        "Photo Booth": "camera.rotate.fill",
        "Photos": "photo.on.rectangle.angled",
        "Photoshop": "paintbrush.pointed.fill",
        "PhpStorm": "sun.horizon.fill",
        "Pi-hole Remote": "circle.hexagongrid.fill",
        "Pixelmator Pro": "photo.badge.plus.fill",
        "Play": "gamecontroller.fill",
        "Plex": "play.fill",
        "Plexamp": "music.note.list",
        "Podcasts": "mic.fill",
        "PomoDone App": "timer",
        "Postico": "elephant.fill",
        "Postman": "paperplane.circle.fill",
        "PowerPoint": "play.square.stack",
        "Premiere": "scissors",
        "Premiere Pro": "scissors",
        "Preview": "magnifyingglass.circle",
        "Pro Tools": "slider.horizontal.below.rectangle.fill",
        "Proton Mail": "envelope.badge.shield.half.filled",
        "Proton Mail Bridge": "envelope.fill",
        "Proton VPN": "shield.lefthalf.filled",
        "ProtonVPN": "shield.lefthalf.filled",
        "Proxyman": "globe.desk",
        "PrusaSlicer": "printer.fill",
        "PyCharm": "python",
        "QGIS": "map.fill",
        "QQ": "message.fill",
        "QQMusic": "music.note",
        "QQ音乐": "music.note",
        "Quantumult X": "shield",
        "QuickTime Player": "play.circle.fill",
        "RStudio": "r.square.fill",
        "Radio Silence": "speaker.slash.fill",
        "Raindrop.io": "drop.fill",
        "Rappels": "list.bullet.clipboard.fill",
        "Raspberry Pi Imager": "sdcard.fill",
        "Raycast": "bolt.horizontal.circle.fill",
        "Rechner": "calculator",
        "Rectangle": "arrow.up.left.and.arrow.down.right.square.fill",
        "Reddit": "alien.fill",
        "RedisInsight": "bolt.horizontal.fill",
        "Reeder": "newspaper.fill",
        "Remind Faster": "bell.fill",
        "Reminders": "list.bullet.clipboard.fill",
        "Replit": "rectangle.split.3x1.fill",
        "Repo Prompt": "terminal.fill",
        "RetroArch": "gamecontroller.fill",
        "Rider": "figure.outdoor.cycle",
        "Royal TSX": "server.rack",
        "RubyMine": "gemstone.fill",
        "Safari": "safari",
        "Safari Technology Preview": "safari",
        "Safari浏览器": "safari",
        "Screen Sharing": "display.2",
        "Scribus": "doc.text.fill",
        "Script Editor": "applescript.fill",
        "Seafile": "cloud.archivebox.fill",
        "Sequel Ace": "cylinder.split.1x2.fill",
        "Sequel Pro": "cylinder.split.1x2.fill",
        "Session": "message.fill",
        "Setapp": "square.stack.3d.up.fill",
        "Shapr3D": "cube.box.fill",
        "Shifty": "moon.stars.fill",
        "Shortcuts": "wrench.adjustable",
        "Sibelius": "music.note.list",
        "Signal": "lock.shield.fill",
        "Simulator": "iphone",
        "Sketch": "square.split.bottomrightquarter",
        "Skype": "phone.connection",
        "Slack": "pound",
        "SnippetsLab": "doc.text.snippet",
        "Sourcetree": "tree",
        "Spark": "envelope.open.fill",
        "Spark Desktop": "envelope.open.fill",
        "Spark Mail": "envelope.fill",
        "Spotify": "circle.grid.2x1",
        "Spotlight": "magnifyingglass.circle.fill",
        "Stats": "chart.bar.fill",
        "Steam": "gamecontroller.fill",
        "Steam Helper": "gamecontroller.fill",
        "Stocks": "chart.line.uptrend.xyaxis.circle.fill",
        "Streamlabs": "video.badge.waveform.fill",
        "Sublime Merge": "git",
        "Sublime Text": "text.word",
        "SuperDuper!": "externaldrive.connected.to.line.below.fill",
        "Superhuman": "envelope.fill",
        "Swift Playground": "gamecontroller.fill",
        "Synology Drive": "server.rack",
        "System Preferences": "gearshape.2.fill",
        "System Settings": "gearshape.2.fill",
        "T3 Chat": "message.fill",
        "TablePlus": "cylinder.split.1x2.fill",
        "TeamSpeak 3": "person.2.wave.2",
        "TeamViewer": "cursorarrow.motionlines.click",
        "Telegram": "paperplane.fill",
        "Terminal": "terminal.fill",
        "TestFlight": "paperplane.fill",
        "TextMate": "text.quotelevel",
        "Things": "circle.hexagongrid.circle",
        "Thunderbird": "bird.fill",
        "Thunderbird Daily": "bird.fill",
        "TikTok": "music.mic",
        "Time Machine": "timelapse",
        "Todoist": "checkmark.seal.fill",
        "Tor Browser": "globe",
        "Transmit": "arrow.left.arrow.right.circle.fill",
        "Tweetbot": "bird.fill",
        "Twilight": "globe",
        "Twitch": "flag.2.crossed.fill",
        "Twitter": "bird.fill",
        "UTM": "cpu",
        "Ubisoft Connect": "hexagon.fill",
        "Ulysses": "text.book.closed.fill",
        "VLC": "traffic.cone",
        "VMware Fusion": "desktopcomputer.and.monitor",
        "VSCode": "curlybraces.square",
        "Viber": "phone.bubble.fill",
        "VirtualBox": "macmini",
        "Visual Studio Code": "curlybraces.square",
        "Vivaldi": "star",
        "Wallet": "wallet.pass.fill",
        "Warp": "command.square",
        "WeChat": "bubble.left.and.bubble.right.fill",
        "Weather": "cloud.sun.fill",
        "WebStorm": "cloud.sun.rain.fill",
        "Webull Desktop": "globe",
        "Wetter": "cloud.sun.fill",
        "WhatsApp": "phone.bubble.left.fill",
        "Wireshark": "magnifyingglass.circle.badge.ellipsis",
        "Word": "doc.text.below.ecg",
        "Xcode": "hammer",
        "Yandex": "globe",
        "Yandex Browser": "globe",
        "Yandex Browser": "globe",
        "Yandex Music": "music.quarternote.3",
        "YouTube": "play.rectangle.on.rectangle.fill",
        "YouTube Music": "music.quarternote.3",
        "Zed": "bolt.horizontal",
        "Zen": "globe",
        "Zen Browser": "globe",
        "Zoom": "video.badge.ellipsis",
        "iA Writer": "pencil.line",
        "iStat Menus": "gauge.with.dots.needle.bottomleft.50percent",
        "iTerm": "terminal.fill",
        "iTerm2": "terminal.fill",
        "iTunes": "music.note.tv",
        "qutebrowser": "globe",
        "zoom.us": "video.badge.ellipsis",
        "‎WhatsApp": "phone.bubble.left.fill",
        "カレンダー": "calendar",
        "ターミナル": "terminal.fill",
        "マップ": "map.fill",
        "ミュージック": "music.quarternote.3",
        "メッセージ": "message.fill",
        "メモ": "note.text",
        "メール": "envelope.fill",
        "リマインダー": "list.bullet.clipboard.fill",
        "信息": "message.fill",
        "备忘录": "note.text",
        "微信": "message.fill",
        "提醒事项": "list.bullet.clipboard.fill",
        "日历": "calendar",
        "终端": "terminal.fill",
        "网易云音乐": "music.note",
        "访达": "folder.fill",
        "邮件": "envelope.fill",
        "钉钉": "message.fill",
        "阿里钉": "message.fill",
        "音乐": "music.quarternote.3",
        "카카오톡": "message.fill",
    ]

    /// Get the SF Symbol name for an app
    static func symbolName(for appName: String?) -> String? {
        guard let appName = appName else { return nil }

        // Direct match
        if let symbol = symbolMappings[appName] {
            return symbol
        }

        // Case-insensitive match
        let lowercased = appName.lowercased()
        for (key, value) in symbolMappings {
            if key.lowercased() == lowercased {
                return value
            }
        }

        // Partial match - check if app name contains any mapped key
        for (key, value) in symbolMappings {
            if lowercased.contains(key.lowercased()) {
                return value
            }
        }

        return nil
    }

    /// Check if an app has a mapped SF Symbol
    static func hasSymbol(for appName: String?) -> Bool {
        return symbolName(for: appName) != nil
    }
}
